# Generated by Django 4.2.6 on 2023-12-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('course', models.IntegerField()),
                ('specialty', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
            ],
        ),
    ]
