# Generated by Django 4.2.6 on 2023-12-06 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorTypeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(blank=True, choices=[('Almaty', 'Алматы'), ('Nur-Sultan', 'Нур-Султан (Астана)'), ('Shymkent', 'Шымкент'), ('Karaganda', 'Караганда'), ('Aktobe', 'Актобе'), ('Taraz', 'Тараз'), ('Pavlodar', 'Павлодар'), ('Ust-Kamenogorsk', 'Усть-Каменогорск'), ('Semey', 'Семей'), ('Atyrau', 'Атырау'), ('Kostanay', 'Костанай'), ('Petropavl', 'Петропавловск'), ('Kyzylorda', 'Кызылорда'), ('Aktau', 'Актау'), ('Uralsk', 'Уральск'), ('Kokshetau', 'Кокшетау'), ('Taldykorgan', 'Талдыкорган'), ('Turkestan', 'Туркестан'), ('Othen', 'Другое')], max_length=100, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, default=1000, max_digits=10, null=True)),
                ('format', models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Оффлайн')], max_length=20)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('telegram', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/mentors')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactWithMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='mentors.mentortypeuser')),
            ],
        ),
    ]
